title: Hache's Wiki
description: Testeando Jekyll como WIki
theme: just-the-docs

url: https://hrandt.github.io/wiki

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
